import { User } from "./types";

export const allUser: User[] = [
  {
    __typename: "user",
    name: "Jabelic",
    uuid: 111029,
    id: "Jabelic_",
    contractType: "free",
    age: 22,
    description: "",
    link: "",
    birthday: new Date(1999 - 5 - 23),
    nationality: "Japan",
    createdAt: "2018-4-10",
    updatedAt: "2022-2-10",
  },
  {
    __typename: "user",
    name: "Rich Harris",
    uuid: 111029,
    id: "Rich_Harris",
    contractType: "tenDollar",
    age: 36,
    description: "",
    link: "https://github.com/Rich-Harris",
    birthday: new Date(1985 - 3 - 10),
    nationality: "Japan",
    createdAt: "2015-7-13",
    updatedAt: "2022-2-9",
  },
  {
    __typename: "user",
    name: "Nikkei",
    uuid: 111029,
    id: "pppchannel",
    contractType: "tenDollar",
    age: 52,
    description: "",
    link: "https://www.nikkei.com/",
    birthday: new Date(1945 - 4 - 3),
    nationality: "Japan",
    createdAt: "2019-4-23",
    updatedAt: "2022-2-5",
  },
];
